apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: analytic-service
  name: analytic-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: analytic-service
