apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - while ! curl -s user-server:8080; do sleep 1; done; nginx -g 'daemon off;'
      image: api-gateway
      name: api-gateway
      ports:
        - containerPort: 443
          protocol: TCP
      resources:
        limits:
          cpu: 500m
  restartPolicy: OnFailure
