apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mongo-task
  name: mongo-task
spec:
  ports:
    - name: "27019"
      port: 27019
      targetPort: 27017
  selector:
    io.kompose.service: mongo-task
