apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mongo-express-task
  name: mongo-express-task
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8081
  selector:
    io.kompose.service: mongo-express-task
