apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mongo-analytics
  name: mongo-analytics
spec:
  ports:
    - name: "27020"
      port: 27020
      targetPort: 27017
  selector:
    io.kompose.service: mongo-analytics
