apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nats
  name: nats
spec:
  selector:
    io.kompose.service: nats
  ports:
    - name: "nats-client"
      port: 4222
      targetPort: 4222
