apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9000
  selector:
    io.kompose.service: sonarqube
