apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: task-server
  name: task-server
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8080
  selector:
    io.kompose.service: task-server
