apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: workflow-server
  name: workflow-server
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8080
  selector:
    io.kompose.service: workflow-server
